In [1]:
import pandas as pd
import numpy as np

In [2]:
list1 = []
for i in range(2,10):
    locals()[f'data{i}'] = pd.read_excel('/Users/malek/Documents/LSEG Data/Korean Returns.xlsx',sheet_name=f'Sheet{i}',index_col=0)
    list1.append(locals()[f'data{i}'])

In [3]:
# list1 contains 8 DataFrames with identical columns but with different time periods
list1 = [i.apply(pd.to_numeric,errors='coerce') for i in list1]
list1 = [i.dropna(axis=1,how='all') for i in list1]
list1 = [i.set_index(pd.to_datetime(i.index,yearfirst=True)) for i in list1]

In [4]:
Korean_Returns = pd.concat(list1, axis=0).sort_index()
Korean_Returns = Korean_Returns.pct_change()
Korean_Returns = Korean_Returns.replace({0:np.nan})
Korean_Returns.columns = Korean_Returns.columns.str.replace(' - TOT RETURN IND','')
Korean_Returns

,SAMSUNG ELECTRONICS,SK HYNIX,POSCO HOLDINGS,LIGNEX1,POSCO FUTURE M,LS CABLE&SYSTEM ASIA,CELLTRION,LG ELECTRONICS,NAVER,SAMSUNG SDI,...,DYLNJ DEAD - DELIST.26/07/16,SGA CLOUDSERVICE DEAD - DELIST.06/05/21,DESIGN POWER & KOREA DEAD - DELIST.30/08/17,MILAE RESOURCES ML DEAD - DELIST.27/12/17,ALOYS DEAD - DELIST.01/10/19,ES INDUSTRY DEAD - DELIST.26/01/21,JSPV DEAD - DELIST.03/03/19,JEONWOO PRECISION DEAD - DELIST.06/05/21,DARIN DEAD - DELIST.02/08/17,CAROS DEAD - DELIST.30/11/17
Name,,,,,,,,,,,,,,,,,,,,,
1990-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-03,0.005512,NaN,-0.015437,NaN,NaN,NaN,NaN,NaN,NaN,-0.031387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-04,0.011164,NaN,0.016046,NaN,NaN,NaN,NaN,NaN,NaN,0.004391,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-05,-0.022067,NaN,-0.009524,NaN,NaN,NaN,NaN,NaN,NaN,-0.032788,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-26,-0.003442,-0.010187,0.012132,0.022626,0.033613,0.005313,0.014452,-0.021985,0.002809,0.003215,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-27,0.003454,NaN,NaN,0.034418,0.024390,0.007927,0.008547,0.008992,0.014006,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-28,-0.019604,-0.009148,0.003421,-0.002167,-0.051323,0.018281,-0.025453,0.004456,-0.005525,-0.032003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-29,-0.022968,-0.013272,-0.049827,0.006515,0.005587,-0.034444,-0.030211,-0.032435,-0.013889,-0.019901,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN